#pragma once

#define TEXTRANSFER_NORMAL
#ifndef TEXTRANSFER_NORMAL
#define TEXTRANSFER_ORTHO
#endif
#define UPDATE_WEIGHTBLENDING
#ifndef UPDATE_WEIGHTBLENDING
#define UPDATE_WINNERTAKESALL
#endif
#define WRITERENDEREDIMAGE

//#define TEST_REGISTRATION
//#define WRITE_RESULT
//#define SHOW_STATUS